### ISSUE TITLE
Issues while building the project

### ISSUE THREAD

**Issue by Amanb1145** [victorges/justcast.it#45]
Hey, 
I found this awesome project today and while I was trying the command `yarn build` I got the following errors-
my node version is v18.13.0 and yarn version is 1.22.19

First I used `yarn`-
logs-
`yarn
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "workspace-aggregator-18b221cc-d877-427c-aa5c-de5a1f4e1151 > justrender-it > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
[4/4] Building fresh packages...
Done in 12.19s.
`
then I used `yarn build`-
logs-
`yarn run v1.22.19
$ mkdir -p dist && concurrently --names server,client 'cd server && yarn build' 'cd client && yarn build'
$ yarn clean; run-p build:copy build:bundle
$ tsc
$ rm -rf ../dist/public
$ rsync -r --exclude '*.ts' src/* ../dist/public
$ run-p build:bundle:transmitter build:bundle:receiver
$ esbuild --define:process.env.NODE_ENV="production" --minify --bundle --log-level=error src/transmitter/index.ts --outfile=../dist/public/transmitter/bundle.js
$ esbuild --define:process.env.NODE_ENV="production" --minify --bundle --log-level=error src/receiver/index.ts --outfile=../dist/public/receiver/bundle.js
[client] cd client && yarn build exited with code 0
[server] cd server && yarn build exited with code 0
Done in 1.62s.`

any ideas ?
Thanks

**Comment by victorges** [comment]
Hey, do you have rsync installed in your system? I believe that's the only
non npm dependency that we have

**Comment by Amanb1145** [comment]
Hey I was able to build this right after I posted this issue that's why I closed the issue. Thanks for your quick response :)
